language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
install:
  - set -x
  - python --version 2>&1 | grep -q " 2." && python bootstrap.py || python bootstrap2.py
  - ./bin/buildout buildout:parts=test
script: python --version 2>&1 | grep -q " 2." && ./bin/py.test || ./bin/py.test build/lib/
